name: Config Workflow v2.3.1

on:
  workflow_dispatch: null

jobs:
  test:
    runs-on: ubuntu-latest
    name: Start Tunnel
    steps:
      - uses: saucelabs/sauce-connect-action@v2.3.1
        with:
          username: "${{ secrets.SAUCE_USERNAME }}"
          accessKey: "${{ secrets.SAUCE_ACCESS_KEY }}"
          region: us-west
          tunnelName: sc-action-test-config
          configFile: ${{ github.workspace }}/sc-configuration/config.yaml
