name: Config Workflow Branch Working

on:
  workflow_dispatch: null

jobs:
  test:
    runs-on: ubuntu-latest
    name: Start Tunnel
    steps:
      - uses: actions/checkout@v3
      - uses: saucelabs/sauce-connect-action@alana-add-missing-log-msg
        with:
          username: "${{ secrets.SAUCE_USERNAME }}"
          accessKey: "${{ secrets.SAUCE_ACCESS_KEY }}"
          region: us-west
          tunnelName: sc-action-test-config
          configFile: ${{ github.workspace }}/sc-configuration/config.yaml
