name: Config Workflow

on:
  workflow_dispatch: null

jobs:
  test:
    runs-on: ubuntu-latest
    name: Start Tunnel
    steps:
      - uses: actions/checkout@v3 # reference files in the current repository
      - uses: saucelabs/sauce-connect-action@main # or use the latest version with @main
        with:
          username: "${{ secrets.SAUCE_USERNAME }}"
          accessKey: "${{ secrets.SAUCE_ACCESS_KEY }}"
          region: us-west
          tunnelName: sc-action-test-config
          configFile: ${{ github.workspace }}/sc-configuration/config.yaml
